before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -y libssl-dev libpcre3-dev libxml2-dev wget unzip libopencore-amrwb0 libopencore-amrnb0 libass5 libgsm1 libmp3lame0 libopenjpeg5 libschroedinger-1.0-0 libspeex1 libtheora0  libva1  libvpx3 libxvidcore4 libnuma1 gcc-7 libvdpau1 libfdk-aac0  libva-drm1 libva-x11-1 libvorbisfile3 libopenjp2-7 libzvbi0
    - wget http://installrepo.origin.kaltura.org/repo/apt/xenial/pool/main/k/kaltura-ffmpeg/kaltura-ffmpeg_4.0.2-3_amd64.deb
    - wget http://installrepo.origin.kaltura.org/repo/apt/xenial/pool/main/x/x264/libx264-148_0.148-1_amd64.deb 
    - wget http://installrepo.origin.kaltura.org/repo/apt/xenial/pool/main/x/x265/libx265-87_2.0-4_amd64.deb 
    - sudo dpkg -i libx264-148_0.148-1_amd64.deb
    - sudo dpkg -i libx265-87_2.0-4_amd64.deb 
    - sudo dpkg -i kaltura-ffmpeg_4.0.2-3_amd64.deb
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 20
language: c
compiler:
    - clang
    - gcc
dist: xenial
env:
  - NGX_VOD_MODULE=--add-module=./nginx-vod-module
  - NGX_VOD_MODULE=--add-dynamic-module=./nginx-vod-module
script: ./travis_build.sh $NGX_VOD_MODULE
notifications:
  email:
    recipients:
      - eran.kornblau@kaltura.com
      - jess.portnoy@kaltura.com
    on_success: change
    on_failure: always
